// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelemetryStash.Database;

#nullable disable

namespace TelemetryStash.Database.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TelemetryStash.Database.Models.Device", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("TelemetryStash.Database.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RegisterIdentifier")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegisterSetId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Unit")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RegisterSetId", "RegisterIdentifier")
                        .IsUnique();

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("TelemetryStash.Database.Models.RegisterKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RegisterId")
                        .HasColumnType("int");

                    b.Property<string>("Subset")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RegisterId", "Subset")
                        .IsUnique();

                    b.ToTable("RegisterKeys");
                });

            modelBuilder.Entity("TelemetryStash.Database.Models.RegisterSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Identifier")
                        .IsUnique();

                    b.ToTable("RegisterSets");
                });

            modelBuilder.Entity("TelemetryStash.Database.Models.Telemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RegisterKeyId")
                        .HasColumnType("int");

                    b.Property<int>("TimestampId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("RegisterKeyId", "TimestampId")
                        .IsUnique();

                    b.ToTable("Telemetries");
                });

            modelBuilder.Entity("TelemetryStash.Database.Models.TelemetryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromTimestampHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("RegisterKeyId")
                        .HasColumnType("int");

                    b.Property<int>("ToTimestampHistoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.ToTable("TelemetryHistory");
                });

            modelBuilder.Entity("TelemetryStash.Database.Models.Timestamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.Property<short>("DeviceId")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("Ts")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Ts")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("DeviceId", "Ts"), false);

                    b.ToTable("TimestampHistory");
                });

            modelBuilder.Entity("TelemetryStash.Database.Models.TimestampHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.Property<short>("DeviceId")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("Ts")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.HasKey("Id");

                    b.ToTable("Timestamps");
                });
#pragma warning restore 612, 618
        }
    }
}
