name: CI/CD Telemetry Stash

on:
  push:
    paths:
      - src/backend/Functions/**
      - src/backend/Database/**
      - '.github/workflows/**'
  pull_request:
    paths:
      - src/backend/Functions/**
      - src/backend/Database/**
      - '.github/workflows/**'
    branches: [ "main" ]

jobs:

  build-and-publish:
    uses: ./.github/workflows/backend-build.yml
    with:
      projectDirectory: src/backend/Functions/Ts.Functions
      artifactsDirectory: src/backend/Functions/Ts.Functions/publish
 
  deploy-dev:
    uses: ./.github/workflows/backend-functions-deploy.yml
    needs: build-and-publish
    with:
      environment: dev
      functionAppName: func-ts-develop
      artifactsDirectory: src/backend/Functions/Ts.Functions/publish
    secrets:
      publishProfile: ${{ secrets.func_ts_develop_5119 }}
 
  deploy-prod:
    uses: ./.github/workflows/backend-functions-deploy.yml
    needs: deploy-dev
    with:
      environment: prod
      functionAppName: func-ts-prod
      artifactsDirectory: src/backend/Functions/Ts.Functions/publish
    secrets:
      publishProfile: ${{ secrets.xxx }}
