name: Build & Test & Publish

on:
  workflow_call:
    inputs:
      test:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test 2
    steps:
    - name: Test Echo
    run: echo "Test Echo Build & Test & Publish pipeline is called"
