name: Deploy backend

on:
  workflow_call:
    inputs:
      deployStage:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - name: Test Echo
      run: echo "Test Echo Deploy pipeline is called"