name: Deploy Functions

on:
  workflow_call:
    inputs:
      artifactsDirectory:
        required: true
        type: string
      environment:
        required: true
        type: string
      functionAppName:
        required: true
        type: string

jobs:
  deploy-functions:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from publish
        uses: actions/download-artifact@v4
        with:
          name: functionapp
          path: ${{ inputs.artifactsDirectory }}
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        id: functionapp
        with:
          app-name: ${{ inputs.functionAppName }}
          publish-profile: ${{ secrets.FUNC_PUBLISH_PROFILE }}
          package: ${{ inputs.artifactsDirectory }}